#!/bin/bash

TYPE=(backlog feat fix docs style refactor test chore)

echo "Select the type of change that you're committing:
    1. backlog: 开始一个新的backlog
    2. feat: 新功能（feature）
    3. fix: 修补bug
    4. docs: 文档（documentation）
    5. style: 格式（不影响代码运行的变动）
    6. refactor: 重构（即不是新增功能，也不是修改bug的代码变动）
    7. test: 增加测试
    8. chore: 构建过程或辅助工具的变动
    0. quit: 退出
"
read -p "Enter selection [0-8]> "

if [[ $REPLY =~ ^[0-8]$ ]]; then
    if [[ $REPLY == 0 ]]; then
        echo "Program Quit."
        exit
    fi
    type=${TYPE[$REPLY-1]}
else
    echo "Invalid entry." >&2
    exit 1
fi

echo 'Denote the scope of this change ($location, $browser, $compile, etc.):'
read -p '' scope
echo "Write a short, imperative tense description of the change:"
read -p '' subject
echo "Provide a longer description of the change:"
read -p '' body
echo "List any breaking changes or issues closed by this change:"
read -p '' footer

SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')

ALL=""
if [[ -z $@ ]]; then
    ALL="-a"
else
    ALL=$@
fi

MSGFILE=".git/COMMIT-MSG.tmp"

echo "$type($scope): $subject" > $MSGFILE
echo "" >> $MSGFILE
echo "$body" >> $MSGFILE
echo "" >> $MSGFILE
echo "$footer" >> $MSGFILE

GIT_COMMIT_CMD="git commit -F $MSGFILE $ALL"

echo $GIT_COMMIT_CMD
eval $GIT_COMMIT_CMD
rm -f $MSGFILE
